<?php

/**
 * @file
 */

/**
 * Update the module weight.
 */
function cms_content_sync_draggableviews_install() {
  // Set module weight higher then the cms_content_sync module to ensure
  // update hooks are triggered after it.
  module_set_weight('cms_content_sync_draggableviews', 20);

  // Clear cache so the new module weight is reflected immediately.
  Drupal::moduleHandler()->resetImplementations();

  return 'Updated module weight to execute hooks after main module.';
}
