<?php

/**
 * @file
 * Module file for cms_content_sync_health.
 */

/**
 * Implements hook_theme().
 */
function cms_content_sync_health_theme() {
  $theme['cms_content_sync_sync_health_overview'] = [
    'variables' => [
      'sync_cores' => NULL,
      'module_version' => NULL,
      'newest_version' => NULL,
      'push_failures_hard' => NULL,
      'push_failures_soft' => NULL,
      'pull_failures_hard' => NULL,
      'pull_failures_soft' => NULL,
      'version_differences' => NULL,
      'site_log_disabled' => NULL,
      'error_log' => NULL,
      'warning_log' => NULL,
    ],
    'template' => 'cms_content_sync_sync_health_overview',
  ];

  $theme['cms_content_sync_sync_health_push'] = [
    'variables' => [
      'push_failures_hard' => NULL,
      'push_failures_soft' => NULL,
      'pending' => NULL,
    ],
    'template' => 'cms_content_sync_sync_health_push',
  ];

  $theme['cms_content_sync_sync_health_pull'] = [
    'variables' => [
      'pull_failures_hard' => NULL,
      'pull_failures_soft' => NULL,
    ],
    'template' => 'cms_content_sync_sync_health_pull',
  ];

  return $theme;
}
